import { useState } from "react";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AlertCircle, CheckCircle2, FileText, Mail, Loader2 } from "lucide-react";
import { useCloseSession, useCheckSessionReadyToClose } from "@/hooks/useCloseSession";
import type { Session } from "@/hooks/useSessions";
import { useEffect } from "react";

interface CloseSessionDialogProps {
  session: Session;
  inscriptions: any[];
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

export function CloseSessionDialog({
  session,
  inscriptions,
  open,
  onOpenChange,
  onSuccess,
}: CloseSessionDialogProps) {
  const [autoGenerateDocuments, setAutoGenerateDocuments] = useState(true);
  const [sendCompletionEmails, setSendCompletionEmails] = useState(true);
  const [emargementsStatus, setEmargementsStatus] = useState<{
    ready: boolean;
    missingCount: number;
    totalInscribed: number;
  } | null>(null);
  const [closeResult, setCloseResult] = useState<{
    success: boolean;
    missingEmargements?: string[];
  } | null>(null);

  const closeSession = useCloseSession();
  const { checkEmargements } = useCheckSessionReadyToClose(session.id);

  useEffect(() => {
    if (open) {
      checkEmargements().then(setEmargementsStatus);
      setCloseResult(null);
    }
  }, [open, session.id]);

  const handleClose = async () => {
    const result = await closeSession.mutateAsync({
      session,
      inscriptions,
      autoGenerateDocuments,
      sendCompletionEmails,
    });

    if (!result.success && result.missingEmargements) {
      setCloseResult(result);
    } else if (result.success) {
      onOpenChange(false);
      onSuccess?.();
    }
  };

  const isReady = emargementsStatus?.ready ?? false;
  const isLoading = closeSession.isPending;

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent className="max-w-md">
        <AlertDialogHeader>
          <AlertDialogTitle>Clôturer la session</AlertDialogTitle>
          <AlertDialogDescription asChild>
            <div className="space-y-4">
              <p>
                Vous êtes sur le point de clôturer la session{" "}
                <strong>{session.nom}</strong>.
              </p>

              {/* Emargements status */}
              <div className="flex items-center gap-2 p-3 rounded-lg bg-muted">
                {emargementsStatus === null ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : isReady ? (
                  <>
                    <CheckCircle2 className="h-5 w-5 text-success" />
                    <span className="text-sm">
                      Tous les stagiaires ont émargé ({emargementsStatus.totalInscribed})
                    </span>
                  </>
                ) : (
                  <>
                    <AlertCircle className="h-5 w-5 text-warning" />
                    <span className="text-sm">
                      {emargementsStatus?.missingCount} stagiaire(s) n'ont pas émargé sur{" "}
                      {emargementsStatus?.totalInscribed}
                    </span>
                  </>
                )}
              </div>

              {/* Warning for missing emargements from close attempt */}
              {closeResult?.missingEmargements && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    <p className="font-medium mb-2">Émargements manquants :</p>
                    <ul className="list-disc list-inside text-sm">
                      {closeResult.missingEmargements.map((name, i) => (
                        <li key={i}>{name}</li>
                      ))}
                    </ul>
                  </AlertDescription>
                </Alert>
              )}

              {/* Options */}
              <div className="space-y-3">
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="generate-docs"
                    checked={autoGenerateDocuments}
                    onCheckedChange={(checked) => setAutoGenerateDocuments(checked === true)}
                  />
                  <Label htmlFor="generate-docs" className="flex items-center gap-2 cursor-pointer">
                    <FileText className="h-4 w-4 text-muted-foreground" />
                    <span>Générer les attestations automatiquement</span>
                  </Label>
                </div>

                <div className="flex items-center space-x-2">
                  <Checkbox
                    id="send-emails"
                    checked={sendCompletionEmails}
                    onCheckedChange={(checked) => setSendCompletionEmails(checked === true)}
                  />
                  <Label htmlFor="send-emails" className="flex items-center gap-2 cursor-pointer">
                    <Mail className="h-4 w-4 text-muted-foreground" />
                    <span>Envoyer un email de fin de session</span>
                  </Label>
                </div>
              </div>

              {/* Summary badges */}
              <div className="flex flex-wrap gap-2">
                <Badge variant="outline" className="bg-primary/10">
                  {inscriptions.length} stagiaire(s)
                </Badge>
                {autoGenerateDocuments && (
                  <Badge variant="outline" className="bg-success/10 text-success">
                    {inscriptions.length} attestation(s)
                  </Badge>
                )}
                {sendCompletionEmails && (
                  <Badge variant="outline" className="bg-info/10 text-info">
                    {inscriptions.filter(i => i.contacts?.email).length} email(s)
                  </Badge>
                )}
              </div>
            </div>
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={isLoading}>Annuler</AlertDialogCancel>
          <AlertDialogAction
            onClick={handleClose}
            disabled={isLoading || !isReady}
            className="bg-primary hover:bg-primary/90"
          >
            {isLoading ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Clôture en cours...
              </>
            ) : (
              "Clôturer la session"
            )}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
