// Liste des départements français pour inscription examen T3P
export const departementsExamenT3P = [
  { code: "75", label: "75 - Paris" },
  { code: "77", label: "77 - Seine-et-Marne" },
  { code: "78", label: "78 - Yvelines" },
  { code: "91", label: "91 - Essonne" },
  { code: "92", label: "92 - Hauts-de-Seine" },
  { code: "93", label: "93 - Seine-Saint-Denis" },
  { code: "94", label: "94 - Val-de-Marne" },
  { code: "95", label: "95 - Val-d'Oise" },
  { code: "13", label: "13 - Bouches-du-Rhône" },
  { code: "69", label: "69 - Rhône" },
  { code: "33", label: "33 - Gironde" },
  { code: "31", label: "31 - Haute-Garonne" },
  { code: "59", label: "59 - Nord" },
  { code: "06", label: "06 - Alpes-Maritimes" },
  { code: "44", label: "44 - Loire-Atlantique" },
  { code: "34", label: "34 - Hérault" },
  { code: "67", label: "67 - Bas-Rhin" },
  { code: "35", label: "35 - Ille-et-Vilaine" },
  { code: "38", label: "38 - Isère" },
  { code: "76", label: "76 - Seine-Maritime" },
  { code: "01", label: "01 - Ain" },
  { code: "02", label: "02 - Aisne" },
  { code: "03", label: "03 - Allier" },
  { code: "04", label: "04 - Alpes-de-Haute-Provence" },
  { code: "05", label: "05 - Hautes-Alpes" },
  { code: "07", label: "07 - Ardèche" },
  { code: "08", label: "08 - Ardennes" },
  { code: "09", label: "09 - Ariège" },
  { code: "10", label: "10 - Aube" },
  { code: "11", label: "11 - Aude" },
  { code: "12", label: "12 - Aveyron" },
  { code: "14", label: "14 - Calvados" },
  { code: "15", label: "15 - Cantal" },
  { code: "16", label: "16 - Charente" },
  { code: "17", label: "17 - Charente-Maritime" },
  { code: "18", label: "18 - Cher" },
  { code: "19", label: "19 - Corrèze" },
  { code: "21", label: "21 - Côte-d'Or" },
  { code: "22", label: "22 - Côtes-d'Armor" },
  { code: "23", label: "23 - Creuse" },
  { code: "24", label: "24 - Dordogne" },
  { code: "25", label: "25 - Doubs" },
  { code: "26", label: "26 - Drôme" },
  { code: "27", label: "27 - Eure" },
  { code: "28", label: "28 - Eure-et-Loir" },
  { code: "29", label: "29 - Finistère" },
  { code: "2A", label: "2A - Corse-du-Sud" },
  { code: "2B", label: "2B - Haute-Corse" },
  { code: "30", label: "30 - Gard" },
  { code: "32", label: "32 - Gers" },
  { code: "36", label: "36 - Indre" },
  { code: "37", label: "37 - Indre-et-Loire" },
  { code: "39", label: "39 - Jura" },
  { code: "40", label: "40 - Landes" },
  { code: "41", label: "41 - Loir-et-Cher" },
  { code: "42", label: "42 - Loire" },
  { code: "43", label: "43 - Haute-Loire" },
  { code: "45", label: "45 - Loiret" },
  { code: "46", label: "46 - Lot" },
  { code: "47", label: "47 - Lot-et-Garonne" },
  { code: "48", label: "48 - Lozère" },
  { code: "49", label: "49 - Maine-et-Loire" },
  { code: "50", label: "50 - Manche" },
  { code: "51", label: "51 - Marne" },
  { code: "52", label: "52 - Haute-Marne" },
  { code: "53", label: "53 - Mayenne" },
  { code: "54", label: "54 - Meurthe-et-Moselle" },
  { code: "55", label: "55 - Meuse" },
  { code: "56", label: "56 - Morbihan" },
  { code: "57", label: "57 - Moselle" },
  { code: "58", label: "58 - Nièvre" },
  { code: "60", label: "60 - Oise" },
  { code: "61", label: "61 - Orne" },
  { code: "62", label: "62 - Pas-de-Calais" },
  { code: "63", label: "63 - Puy-de-Dôme" },
  { code: "64", label: "64 - Pyrénées-Atlantiques" },
  { code: "65", label: "65 - Hautes-Pyrénées" },
  { code: "66", label: "66 - Pyrénées-Orientales" },
  { code: "68", label: "68 - Haut-Rhin" },
  { code: "70", label: "70 - Haute-Saône" },
  { code: "71", label: "71 - Saône-et-Loire" },
  { code: "72", label: "72 - Sarthe" },
  { code: "73", label: "73 - Savoie" },
  { code: "74", label: "74 - Haute-Savoie" },
  { code: "79", label: "79 - Deux-Sèvres" },
  { code: "80", label: "80 - Somme" },
  { code: "81", label: "81 - Tarn" },
  { code: "82", label: "82 - Tarn-et-Garonne" },
  { code: "83", label: "83 - Var" },
  { code: "84", label: "84 - Vaucluse" },
  { code: "85", label: "85 - Vendée" },
  { code: "86", label: "86 - Vienne" },
  { code: "87", label: "87 - Haute-Vienne" },
  { code: "88", label: "88 - Vosges" },
  { code: "89", label: "89 - Yonne" },
  { code: "90", label: "90 - Territoire de Belfort" },
  { code: "971", label: "971 - Guadeloupe" },
  { code: "972", label: "972 - Martinique" },
  { code: "973", label: "973 - Guyane" },
  { code: "974", label: "974 - La Réunion" },
  { code: "976", label: "976 - Mayotte" },
];

// Les départements les plus courants pour les inscriptions T3P (Île-de-France en priorité)
export const departementsPopulaires = ["75", "92", "93", "94", "77", "78", "91", "95", "69", "13", "33", "31"];

export function getDepartementLabel(code: string | null | undefined): string {
  if (!code) return "";
  const dept = departementsExamenT3P.find(d => d.code === code);
  return dept?.label || code;
}
