import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useDocumentGenerator, type DocumentType } from "./useDocumentGenerator";
import type { Session } from "./useSessions";
import type { Contact } from "./useContacts";

interface CloseSessionResult {
  success: boolean;
  missingEmargements?: string[];
  missingDocuments?: string[];
  documentsGenerated?: number;
  emailsSent?: number;
  enquetesSent?: number;
}

interface CloseSessionParams {
  session: Session;
  inscriptions: any[];
  autoGenerateDocuments?: boolean;
  sendCompletionEmails?: boolean;
  sendSatisfactionSurveys?: boolean;
}

export function useCloseSession() {
  const queryClient = useQueryClient();
  const { generateDocument } = useDocumentGenerator();

  return useMutation({
    mutationFn: async ({
      session,
      inscriptions,
      autoGenerateDocuments = true,
      sendCompletionEmails = true,
      sendSatisfactionSurveys = true,
    }: CloseSessionParams): Promise<CloseSessionResult> => {
      console.log("Starting session close process for:", session.id);

      // 1. Vérifier les émargements
      const { data: emargements, error: emargementsError } = await supabase
        .from("emargements")
        .select("contact_id, present")
        .eq("session_id", session.id)
        .eq("present", true);

      if (emargementsError) throw emargementsError;

      const emargedContactIds = new Set(emargements?.map(e => e.contact_id) || []);
      const inscribedContactIds = inscriptions.map(i => i.contact_id);
      
      const missingEmargements = inscribedContactIds.filter(id => !emargedContactIds.has(id));
      
      if (missingEmargements.length > 0) {
        // Get names of contacts missing emargements
        const { data: missingContacts } = await supabase
          .from("contacts")
          .select("id, nom, prenom")
          .in("id", missingEmargements);
        
        const missingNames = missingContacts?.map(c => `${c.prenom} ${c.nom}`) || [];
        
        return {
          success: false,
          missingEmargements: missingNames,
        };
      }

      // 2. Générer les attestations si demandé
      let documentsGenerated = 0;
      if (autoGenerateDocuments) {
        const sessionInfo = {
          nom: session.nom,
          formation_type: session.formation_type,
          date_debut: session.date_debut,
          date_fin: session.date_fin,
          lieu: session.lieu || undefined,
          duree_heures: session.duree_heures || 35,
          prix: session.prix ? Number(session.prix) : undefined,
        };

        for (const inscription of inscriptions) {
          const contact = inscription.contacts as unknown as Contact;
          if (!contact) continue;

          try {
            const contactInfo = {
              civilite: contact.civilite || undefined,
              nom: contact.nom,
              prenom: contact.prenom,
              email: contact.email || undefined,
              telephone: contact.telephone || undefined,
              rue: contact.rue || undefined,
              code_postal: contact.code_postal || undefined,
              ville: contact.ville || undefined,
              date_naissance: contact.date_naissance || undefined,
              ville_naissance: contact.ville_naissance || undefined,
            };

            // Generate attestation (the generateDocument function handles download)
            generateDocument("attestation" as DocumentType, contactInfo, sessionInfo);
            documentsGenerated++;
          } catch (error) {
            console.error(`Error generating attestation for contact ${contact.id}:`, error);
          }
        }
      }

      // 3. Mettre à jour le statut de la session
      const { error: updateError } = await supabase
        .from("sessions")
        .update({ statut: "terminee" })
        .eq("id", session.id);

      if (updateError) throw updateError;

      // 4. Envoyer les emails de fin de session si demandé
      let emailsSent = 0;
      if (sendCompletionEmails) {
        for (const inscription of inscriptions) {
          const contact = inscription.contacts as unknown as Contact;
          if (!contact?.email) continue;

          try {
            // Log email (actual sending would be via edge function)
            await supabase.from("email_logs").insert({
              type: "session_completed",
              recipient_email: contact.email,
              recipient_name: `${contact.prenom} ${contact.nom}`,
              contact_id: contact.id,
              session_id: session.id,
              subject: `Session terminée - ${session.nom}`,
              template_used: "session_completed",
              status: "pending",
            });
            emailsSent++;
          } catch (error) {
            console.error(`Error logging email for contact ${contact.id}:`, error);
          }
        }
      }

      // 5. Envoyer les enquêtes de satisfaction si demandé
      let enquetesSent = 0;
      if (sendSatisfactionSurveys) {
        for (const inscription of inscriptions) {
          const contact = inscription.contacts as unknown as Contact;
          if (!contact?.email) continue;

          try {
            // Créer le token d'enquête
            const { data: tokenData, error: tokenError } = await supabase
              .from("enquete_tokens")
              .insert({
                contact_id: contact.id,
                session_id: session.id,
                type: "satisfaction",
              })
              .select("token")
              .single();

            if (tokenError) {
              console.error(`Error creating enquete token for contact ${contact.id}:`, tokenError);
              continue;
            }

            // Envoyer l'email via edge function
            const enqueteUrl = `${window.location.origin}/enquete/${tokenData.token}`;
            
            const response = await supabase.functions.invoke("send-enquete-email", {
              body: {
                to: contact.email,
                name: `${contact.prenom} ${contact.nom}`,
                enqueteUrl,
                type: "satisfaction",
                sessionName: session.nom,
              },
            });

            if (!response.error) {
              enquetesSent++;
              // Logger l'envoi
              await supabase.from("email_logs").insert({
                type: "enquete_satisfaction",
                recipient_email: contact.email,
                recipient_name: `${contact.prenom} ${contact.nom}`,
                contact_id: contact.id,
                session_id: session.id,
                subject: "Donnez-nous votre avis sur votre formation",
                status: "sent",
              });
            }
          } catch (error) {
            console.error(`Error sending enquete to contact ${contact.id}:`, error);
          }
        }
      }

      return {
        success: true,
        documentsGenerated,
        emailsSent,
        enquetesSent,
      };
    },
    onSuccess: (result, variables) => {
      if (result.success) {
        queryClient.invalidateQueries({ queryKey: ["sessions"] });
        queryClient.invalidateQueries({ queryKey: ["session", variables.session.id] });
        
        let message = "Session clôturée avec succès";
        if (result.documentsGenerated && result.documentsGenerated > 0) {
          message += ` - ${result.documentsGenerated} attestation(s) générée(s)`;
        }
        if (result.emailsSent && result.emailsSent > 0) {
          message += ` - ${result.emailsSent} email(s) programmé(s)`;
        }
        if (result.enquetesSent && result.enquetesSent > 0) {
          message += ` - ${result.enquetesSent} enquête(s) envoyée(s)`;
        }
        toast.success(message);
      }
    },
    onError: (error: Error) => {
      toast.error("Erreur lors de la clôture: " + error.message);
    },
  });
}

export function useCheckSessionReadyToClose(sessionId: string | null) {
  return {
    checkEmargements: async (): Promise<{ ready: boolean; missingCount: number; totalInscribed: number }> => {
      if (!sessionId) return { ready: false, missingCount: 0, totalInscribed: 0 };

      // Get inscriptions
      const { data: inscriptions } = await supabase
        .from("session_inscriptions")
        .select("contact_id")
        .eq("session_id", sessionId);

      // Get emargements with at least one presence
      const { data: emargements } = await supabase
        .from("emargements")
        .select("contact_id")
        .eq("session_id", sessionId)
        .eq("present", true);

      const inscribedCount = inscriptions?.length || 0;
      const emargedContactIds = new Set(emargements?.map(e => e.contact_id) || []);
      const missingCount = (inscriptions || []).filter(i => !emargedContactIds.has(i.contact_id)).length;

      return {
        ready: missingCount === 0 && inscribedCount > 0,
        missingCount,
        totalInscribed: inscribedCount,
      };
    },
  };
}
